name: setiket
description: SeTiket provide a seamless and user-friendly experience for event organizers and customers
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.5
  dio: ^5.2.1+1
  flutter:
    sdk: flutter
  flutter_animate: ^4.2.0
  flutter_dotenv: ^5.1.0
  flutter_screenutil: ^5.8.4
  flutter_svg: ^2.0.7
  font_awesome_flutter: ^10.5.0
  fpdart: ^0.6.0
  freezed: ^2.4.1
  freezed_annotation: ^2.4.1
  go_router: ^9.0.3
  hexcolor: ^3.0.1
  hooks_riverpod: ^2.3.6
  intl: ^0.18.1
  json_annotation: ^4.8.1
  logger: ^1.4.0
  palette_generator: ^0.3.3+2
  quickalert: ^1.0.1
  riverpod_lint: ^1.3.2

dev_dependencies:
  build_runner: 2.4.6
  flutter_launcher_icons: ^0.13.1
  custom_lint: 0.4.0
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  json_serializable: 6.7.1
  riverpod_generator: ^2.2.3

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/icons/
    - assets/fonts/Poppins-Bold.ttf
    - assets/fonts/Poppins-BoldItalic.ttf
    - assets/fonts/Poppins-Italic.ttf
    - assets/fonts/Poppins-Medium.ttf

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-BoldItalic.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
          style: italic
